// ─── Site-wide SEO / AEO / GEO constants ───

/** Dynamic freshness signal. Updated on every build. */
export const LAST_UPDATED = new Date().toISOString().slice(0, 10);

/** Default offer validity — 18 months out, recomputed at build/request time. */
export const DEFAULT_PRICE_VALID_UNTIL = new Date(
  Date.now() + 18 * 30 * 24 * 60 * 60 * 1000,
)
  .toISOString()
  .slice(0, 10);

export const SITE = {
  name: 'Taj Mahal Photography',
  url: 'https://tajmahalphotography.com',
  domain: 'tajmahalphotography.com',
  title: 'Official Government Licensed Taj Mahal Photographer | Agra, India',
  description:
    'Book an official government-licensed Taj Mahal photographer in Agra, India. Authorized permit holder for professional photography inside the Taj Mahal. Sunrise, couple, pre-wedding and guided photo tours with 48-hour delivery.',
  phone: '+918393010125',
  phoneDisplay: '+91 83930 10125',
  email: 'booking@tajmahalphotography.com',
  whatsapp: '918393010125',
  /**
   * Canonical Google Business link, by place CID rather than a short link.
   * Several Agra photographers use near-identical names, and a shortened URL
   * gives no way to tell from the code which profile it opens; the CID can
   * only ever resolve to this one — "Tajmahal Photography", Agra
   * (0x39747131e3553055:0x7e4e33174e3dd711).
   */
  googleBusiness: 'https://maps.google.com/?cid=9101268072152291089',
  /**
   * Rating as shown on the profile. Kept here so the figure on the page and
   * the figure on Google cannot drift apart silently — update both together.
   * Deliberately NOT emitted as AggregateRating schema: Google does not allow
   * a business to mark up reviews of itself on its own site.
   */
  googleRating: 4.7,
  googleReviewCount: 13,
  googleRatingChecked: '21 September 2026',
  instagram: 'https://www.instagram.com/taj.mahal.photography',
  linkedin: 'https://www.linkedin.com/in/taj-mahal-photography-3a9ab0296/',
  facebook: 'https://www.facebook.com/share/19m7nwKSSQ/?mibextid=wwXIfr',
  address: {
    street: 'Taj Mahal East Gate Road',
    city: 'Agra',
    state: 'Uttar Pradesh',
    zip: '282001',
    country: 'IN',
  },
  geo: { lat: 27.1751, lng: 78.0421 },
  locale: 'en_US',
  currency: 'USD',
  /** Branded share card generated by app/opengraph-image.tsx. */
  image: 'https://tajmahalphotography.com/opengraph-image',
  /** Brand mark generated by app/icon.tsx — used as the schema.org logo. */
  logo: 'https://tajmahalphotography.com/icon',
  /** @deprecated use DEFAULT_PRICE_VALID_UNTIL (dynamic). Kept for backwards compat. */
  priceValidUntil: DEFAULT_PRICE_VALID_UNTIL,
} as const;

// ─── Entity references (Wikidata / Wikipedia) for sameAs graph ───
// Wikidata Q-IDs give AI rerankers a verifiable entity edge.
export const ENTITIES = {
  tajMahal: {
    name: 'Taj Mahal',
    wikidata: 'https://www.wikidata.org/wiki/Q9141',
    wikipedia: 'https://en.wikipedia.org/wiki/Taj_Mahal',
    geo: { lat: 27.1751, lng: 78.0421 },
  },
  agraFort: {
    name: 'Agra Fort',
    wikidata: 'https://www.wikidata.org/wiki/Q43473',
    wikipedia: 'https://en.wikipedia.org/wiki/Agra_Fort',
    geo: { lat: 27.1795, lng: 78.0211 },
  },
  agra: {
    name: 'Agra',
    wikidata: 'https://www.wikidata.org/wiki/Q42941',
    wikipedia: 'https://en.wikipedia.org/wiki/Agra',
  },
  delhi: {
    name: 'Delhi',
    wikidata: 'https://www.wikidata.org/wiki/Q1353',
    wikipedia: 'https://en.wikipedia.org/wiki/Delhi',
  },
  ministryOfTourism: {
    name: 'Ministry of Tourism, Government of India',
    wikidata: 'https://www.wikidata.org/wiki/Q6868810',
    url: 'https://tourism.gov.in/',
  },
} as const;

// ─── Reusable JSON-LD generators ───

export function localBusinessSchema() {
  return {
    '@context': 'https://schema.org',
    '@type': ['LocalBusiness', 'ProfessionalService', 'PhotographyBusiness'],
    '@id': `${SITE.url}/#business`,
    name: SITE.name,
    alternateName: ['Taj Mahal Photographer', 'Official Taj Mahal Photographer Agra'],
    image: SITE.image,
    logo: SITE.logo,
    description: SITE.description,
    slogan: 'Official Government Licensed Taj Mahal Photographer',
    url: SITE.url,
    telephone: SITE.phone,
    email: SITE.email,
    priceRange: '$$$',
    currenciesAccepted: 'USD, INR',
    paymentAccepted: 'Cash, UPI, Bank Transfer',
    knowsLanguage: ['en', 'hi', 'ur'],
    address: {
      '@type': 'PostalAddress',
      streetAddress: SITE.address.street,
      addressLocality: SITE.address.city,
      addressRegion: SITE.address.state,
      postalCode: SITE.address.zip,
      addressCountry: SITE.address.country,
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: SITE.geo.lat,
      longitude: SITE.geo.lng,
    },
    hasMap: SITE.googleBusiness,
    contactPoint: {
      '@type': 'ContactPoint',
      contactType: 'reservations',
      telephone: SITE.phone,
      email: SITE.email,
      availableLanguage: ['en', 'hi', 'ur'],
      areaServed: 'IN',
    },
    areaServed: [
      {
        '@type': 'City',
        name: ENTITIES.agra.name,
        sameAs: [ENTITIES.agra.wikipedia, ENTITIES.agra.wikidata],
      },
      {
        '@type': 'City',
        name: ENTITIES.delhi.name,
        sameAs: [ENTITIES.delhi.wikipedia, ENTITIES.delhi.wikidata],
      },
    ],
    knowsAbout: [
      { '@type': 'TouristAttraction', name: ENTITIES.tajMahal.name, sameAs: [ENTITIES.tajMahal.wikipedia, ENTITIES.tajMahal.wikidata] },
      { '@type': 'TouristAttraction', name: ENTITIES.agraFort.name, sameAs: [ENTITIES.agraFort.wikipedia, ENTITIES.agraFort.wikidata] },
    ],
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Saturday', 'Sunday'],
      opens: '05:30',
      closes: '19:00',
    },
    // AggregateRating intentionally omitted — Google policy requires the
    // aggregate to reflect Review nodes actually accessible on the page.
    // Re-enable once verifiable Google/TripAdvisor reviews are wired in.
    parentOrganization: {
      '@type': 'Organization',
      name: 'Taj Guides & Travel Services',
      url: 'https://tajmahaltouristguide.com',
      sameAs: ['https://tajmahaltouristguide.com'],
    },
    sameAs: [SITE.googleBusiness, SITE.instagram, SITE.linkedin, SITE.facebook, 'https://tajmahaltouristguide.com', 'https://guideindiatours.com', 'https://www.asiabylocals.com'],
    hasOfferCatalog: {
      '@type': 'OfferCatalog',
      name: 'Taj Mahal Photography & Tour Packages',
      itemListElement: [
        offerSchema('Taj Mahal Sunrise Photoshoot', 120, 'Avoid crowds, best light. 1.5–2 hour session, 120+ photos, 3–5 reels. Photographer meets you at your hotel; no transport included.', `${SITE.url}/services/sunrise`),
        offerSchema('Pre-Wedding & Couple Photography', 199, 'Editorial romance at the monument of love. 2+ hours, 200+ high-resolution photos, 30 edited photos of your choice, 30-second cinematic video.', `${SITE.url}/services/couple`),
        offerSchema('Taj Mahal + Agra Fort Heritage Trail', 399, 'Both UNESCO sites in one day. 5 hours, 250+ natural high-resolution photos, transport included.', `${SITE.url}/services/taj-agra-fort`),
        offerSchema('Full Day Agra Experience', 499, 'Taj Mahal, Agra Fort & back side coverage. 8-10 hours, 350+ natural high-resolution photos, 48-hour delivery.', `${SITE.url}/services/full-day`),
        offerSchema('Guided Tour + Photo Combo (Small Group, 1–5 Guests)', 89, 'Licensed local guide and professional photographer both included, covering Taj Mahal, Agra Fort & Mehtab Bagh / Itmad-ud-Daulah for up to 5 guests. 40 natural digital photos + 5 reels. Inside the Taj Mahal the photographer accompanies you, as guides are not permitted alongside one. Monument tickets not included.', `${SITE.url}/services/guided-photo-tour-small`),
        offerSchema('Guided Tour + Photo Combo (Large Group, 6–12 Guests)', 119, 'Licensed local guide and professional photographer both included, covering Taj Mahal, Agra Fort & Mehtab Bagh / Itmad-ud-Daulah for groups of 6 to 12. Group + individual portraits, 60 digital photos + 7 reels. Inside the Taj Mahal the photographer accompanies you, as guides are not permitted alongside one. Monument tickets not included.', `${SITE.url}/services/guided-photo-tour-large`),
        offerSchema('Transport + Guide (Private Car, No Photography)', 99, 'Same-day Agra tour: private A/C car with chauffeur plus a Ministry of Tourism licensed guide, starting from $99 USD. Covers Taj Mahal, Agra Fort, Itmad-ud-Daulah and Mehtab Bagh with hotel, railway station or airport pickup; exact quote confirmed on WhatsApp. No photographer. Monument tickets not included.', `${SITE.url}/services/transport-guide`),
        offerSchema('Taj Mahal Sunrise Luxury Tour (Private Innova)', 650, 'Same-day sunrise tour from Delhi/NCR to Agra in a private Toyota Innova. Includes Ministry of Tourism licensed guide and photographer, Taj Mahal & Agra Fort tickets, private golf cart inside the complex, and skip-the-line security escort.', `${SITE.url}/services/sunrise-luxury-innova`),
        offerSchema('Taj Mahal Sunrise Luxury Urbania Tour', 899, 'Same-day sunrise tour from Delhi/NCR to Agra in a private Force Urbania luxury coach for families and groups (up to 13 guests). Includes guide, photographer, Taj Mahal & Agra Fort tickets, golf cart, and skip-the-line security escort.', `${SITE.url}/services/sunrise-luxury-urbania`),
      ],
    },
  };
}

export function offerSchema(name: string, price: number, description: string, url: string) {
  return {
    '@type': 'Offer',
    name,
    price,
    priceCurrency: 'USD',
    description,
    url,
    availability: 'https://schema.org/LimitedAvailability',
    priceValidUntil: SITE.priceValidUntil,
    seller: { '@id': `${SITE.url}/#business` },
  };
}

export function websiteSchema() {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    '@id': `${SITE.url}/#website`,
    name: SITE.name,
    url: SITE.url,
    description: SITE.description,
    publisher: { '@id': `${SITE.url}/#business` },
    potentialAction: {
      '@type': 'SearchAction',
      target: `${SITE.url}/services?q={search_term_string}`,
      'query-input': 'required name=search_term_string',
    },
  };
}

export function breadcrumbSchema(items: { name: string; url: string }[]) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: items.map((item, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: item.name,
      item: item.url,
    })),
  };
}

export function faqSchema(faqs: { question: string; answer: string }[]) {
  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqs.map((faq) => ({
      '@type': 'Question',
      name: faq.question,
      acceptedAnswer: {
        '@type': 'Answer',
        text: faq.answer,
      },
    })),
  };
}

export function serviceSchema(
  name: string,
  description: string,
  price: number,
  duration: string,
  url: string,
  image: string,
) {
  return {
    '@context': 'https://schema.org',
    '@type': 'TouristTrip',
    name,
    description,
    touristType: 'International Visitor',
    provider: { '@id': `${SITE.url}/#business` },
    offers: {
      '@type': 'Offer',
      price,
      priceCurrency: 'USD',
      availability: 'https://schema.org/LimitedAvailability',
      url,
    },
    image,
    itinerary: {
      '@type': 'ItemList',
      description: `Duration: ${duration}`,
    },
  };
}

export function articleSchema(
  title: string,
  description: string,
  url: string,
  datePublished: string,
  image: string,
) {
  return {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: title,
    description,
    url,
    datePublished,
    dateModified: datePublished,
    author: { '@id': `${SITE.url}/#business` },
    publisher: { '@id': `${SITE.url}/#business` },
    image,
    mainEntityOfPage: url,
  };
}

export function personSchema() {
  return {
    '@context': 'https://schema.org',
    '@type': 'Person',
    '@id': `${SITE.url}/#photographer`,
    name: 'Taj Mahal Photography',
    jobTitle: 'Government-Licensed Taj Mahal Photographer',
    description: 'Official Ministry of Tourism certified photographer specializing in Taj Mahal photoshoots, pre-wedding photography, and heritage monument photography in Agra, India.',
    url: SITE.url,
    image: SITE.image,
    telephone: SITE.phone,
    email: SITE.email,
    knowsLanguage: ['en', 'hi', 'ur'],
    nationality: { '@type': 'Country', name: 'India' },
    address: {
      '@type': 'PostalAddress',
      streetAddress: SITE.address.street,
      addressLocality: SITE.address.city,
      addressRegion: SITE.address.state,
      postalCode: SITE.address.zip,
      addressCountry: SITE.address.country,
    },
    workLocation: {
      '@type': 'Place',
      name: ENTITIES.tajMahal.name,
      sameAs: [ENTITIES.tajMahal.wikipedia, ENTITIES.tajMahal.wikidata],
    },
    knowsAbout: [
      'Taj Mahal Photography',
      'Mughal Architecture',
      'Heritage Monument Photography',
      'Pre-Wedding Photography',
      'Sunrise Photography',
      'Government Photography Permits India',
      'Agra Fort Photography',
      'Couple Portrait Photography',
      'Destination Wedding Photography',
      'Travel Photography India',
    ],
    hasCredential: {
      '@type': 'EducationalOccupationalCredential',
      credentialCategory: 'License',
      name: 'Ministry of Tourism Photography License',
      recognizedBy: {
        '@type': 'GovernmentOrganization',
        name: ENTITIES.ministryOfTourism.name,
        sameAs: [ENTITIES.ministryOfTourism.url, ENTITIES.ministryOfTourism.wikidata],
      },
    },
    worksFor: { '@id': `${SITE.url}/#business` },
    sameAs: [SITE.googleBusiness, SITE.instagram, SITE.linkedin, SITE.facebook, 'https://tajmahaltouristguide.com', 'https://guideindiatours.com', 'https://www.asiabylocals.com'],
  };
}

// ─── Schemas for AI answer engines (Perplexity, ChatGPT, Claude, AI Overviews) ───

/** TouristAttraction node for the Taj Mahal — explicit graph edge to the entity. */
export function tajMahalAttractionSchema() {
  return {
    '@context': 'https://schema.org',
    '@type': 'TouristAttraction',
    '@id': `${SITE.url}/#taj-mahal`,
    name: ENTITIES.tajMahal.name,
    alternateName: ['Crown of the Palace', 'Tāj Mahal'],
    description:
      'A 17th-century white-marble mausoleum on the south bank of the Yamuna in Agra, India, commissioned by Mughal emperor Shah Jahan in memory of his wife Mumtaz Mahal. UNESCO World Heritage Site and one of the New Seven Wonders of the World.',
    image: SITE.image,
    sameAs: [ENTITIES.tajMahal.wikipedia, ENTITIES.tajMahal.wikidata],
    geo: { '@type': 'GeoCoordinates', latitude: ENTITIES.tajMahal.geo.lat, longitude: ENTITIES.tajMahal.geo.lng },
    isAccessibleForFree: false,
    publicAccess: true,
    tourBookingPage: `${SITE.url}/book`,
  };
}

/** TouristAttraction node for Agra Fort. */
export function agraFortAttractionSchema() {
  return {
    '@context': 'https://schema.org',
    '@type': 'TouristAttraction',
    '@id': `${SITE.url}/#agra-fort`,
    name: ENTITIES.agraFort.name,
    description:
      'A 16th-century red sandstone Mughal fort and UNESCO World Heritage Site in Agra, India. Built by Emperor Akbar between 1565 and 1573; the principal residence of the Mughal emperors until 1638.',
    sameAs: [ENTITIES.agraFort.wikipedia, ENTITIES.agraFort.wikidata],
    geo: { '@type': 'GeoCoordinates', latitude: ENTITIES.agraFort.geo.lat, longitude: ENTITIES.agraFort.geo.lng },
    isAccessibleForFree: false,
    publicAccess: true,
  };
}

/** Vehicle schema used inside TouristTrip for the Delhi luxury tours. */
export function vehicleSchema(model: 'innova' | 'urbania') {
  if (model === 'innova') {
    return {
      '@type': 'Vehicle',
      name: 'Toyota Innova',
      brand: { '@type': 'Brand', name: 'Toyota' },
      vehicleModelDate: '2024',
      vehicleConfiguration: 'Private chauffeur-driven SUV',
      bodyType: 'SUV',
      seatingCapacity: 6,
      fuelType: 'Diesel',
      vehicleInteriorColor: 'Beige',
    };
  }
  return {
    '@type': 'Vehicle',
    name: 'Force Urbania',
    brand: { '@type': 'Brand', name: 'Force Motors' },
    vehicleModelDate: '2024',
    vehicleConfiguration: 'Private chauffeur-driven luxury minibus',
    bodyType: 'Minibus',
    seatingCapacity: 13,
    fuelType: 'Diesel',
    vehicleInteriorFeatures: 'Reclining seats, A/C, Wi-Fi',
  };
}

/** Full TouristTrip schema for the two Delhi-to-Agra luxury tours. */
export function luxuryTourSchema(opts: {
  slug: 'sunrise-luxury-innova' | 'sunrise-luxury-urbania';
  name: string;
  description: string;
  price: number;
  image: string;
  vehicle: 'innova' | 'urbania';
  audience: string;
}) {
  return {
    '@context': 'https://schema.org',
    '@type': 'TouristTrip',
    '@id': `${SITE.url}/services/${opts.slug}#tour`,
    name: opts.name,
    description: opts.description,
    image: opts.image,
    url: `${SITE.url}/services/${opts.slug}`,
    touristType: ['International Visitor', 'Family Travel', 'Couple Travel'],
    audience: { '@type': 'Audience', audienceType: opts.audience },
    provider: { '@id': `${SITE.url}/#business` },
    offers: {
      '@type': 'Offer',
      price: opts.price,
      priceCurrency: 'USD',
      availability: 'https://schema.org/LimitedAvailability',
      priceValidUntil: SITE.priceValidUntil,
      url: `${SITE.url}/services/${opts.slug}`,
      seller: { '@id': `${SITE.url}/#business` },
      validFrom: '2026-01-01',
      eligibleRegion: [
        { '@type': 'Country', name: 'United States' },
        { '@type': 'Country', name: 'United Kingdom' },
        { '@type': 'Country', name: 'Australia' },
        { '@type': 'Country', name: 'Canada' },
        { '@type': 'Country', name: 'Germany' },
        { '@type': 'Country', name: 'France' },
        { '@type': 'Country', name: 'India' },
      ],
    },
    vehicle: vehicleSchema(opts.vehicle),
    departureLocation: {
      '@type': 'Place',
      name: 'Delhi / NCR (hotel pickup)',
      address: { '@type': 'PostalAddress', addressLocality: 'Delhi', addressCountry: 'IN' },
      sameAs: [ENTITIES.delhi.wikipedia, ENTITIES.delhi.wikidata],
    },
    arrivalLocation: {
      '@type': 'Place',
      name: 'Delhi / NCR (hotel drop)',
      address: { '@type': 'PostalAddress', addressLocality: 'Delhi', addressCountry: 'IN' },
    },
    itinerary: {
      '@type': 'ItemList',
      numberOfItems: 5,
      itemListElement: [
        { '@type': 'ListItem', position: 1, item: { '@type': 'Place', name: 'Hotel pickup in Delhi/NCR (02:30 AM)' } },
        { '@type': 'ListItem', position: 2, item: { '@type': 'TouristAttraction', '@id': `${SITE.url}/#taj-mahal`, name: ENTITIES.tajMahal.name, sameAs: [ENTITIES.tajMahal.wikipedia, ENTITIES.tajMahal.wikidata] } },
        { '@type': 'ListItem', position: 3, item: { '@type': 'FoodEstablishment', name: 'Breakfast at heritage hotel in Agra' } },
        { '@type': 'ListItem', position: 4, item: { '@type': 'TouristAttraction', '@id': `${SITE.url}/#agra-fort`, name: ENTITIES.agraFort.name, sameAs: [ENTITIES.agraFort.wikipedia, ENTITIES.agraFort.wikidata] } },
        { '@type': 'ListItem', position: 5, item: { '@type': 'Place', name: 'Return drop in Delhi/NCR (~7-8 PM)' } },
      ],
    },
    subjectOf: [
      { '@id': `${SITE.url}/#taj-mahal` },
      { '@id': `${SITE.url}/#agra-fort` },
    ],
  };
}

/**
 * Individual Review JSON-LD (so AI engines can extract verbatim quotes).
 *
 * NOTE: Google's structured-data policy prohibits sites from publishing reviews
 * about themselves and surfacing them as rich results. These nodes are emitted
 * as plain customer testimonials (no `publisher`, no `aggregateRating`
 * cross-reference) so AI extractors can still cite the verbatim quotes, but
 * Google won't treat them as eligible for review rich results. Once external
 * Google/TripAdvisor URLs are available, pass them in `sourceUrl`.
 */
export function reviewSchema(opts: {
  author: string;
  country: string;
  body: string;
  rating: number;
  datePublished: string;
  sourceUrl?: string;
}) {
  return {
    '@type': 'Review',
    author: {
      '@type': 'Person',
      name: opts.author,
      nationality: { '@type': 'Country', name: opts.country },
    },
    datePublished: opts.datePublished,
    reviewBody: opts.body,
    reviewRating: {
      '@type': 'Rating',
      ratingValue: opts.rating,
      bestRating: 5,
      worstRating: 1,
    },
    ...(opts.sourceUrl ? { url: opts.sourceUrl } : {}),
  };
}

/** Speakable schema — marks extractable answer passages for voice/AI. */
/**
 * One photograph, described for image search.
 *
 * Google Images is a real channel for a photography business and it ranks on
 * what surrounds a file, not on the pixels: a caption, what the picture is
 * of, where it was taken, who made it and what licence it carries. Emitting
 * this per frame is the difference between eighteen anonymous JPEGs and
 * eighteen indexed photographs of a named landmark.
 */
export function imageObjectSchema(opts: {
  url: string;
  caption: string;
  contentLocation?: string;
}) {
  return {
    '@type': 'ImageObject',
    contentUrl: opts.url,
    url: opts.url,
    caption: opts.caption,
    description: opts.caption,
    representativeOfPage: false,
    creator: { '@id': `${SITE.url}/#photographer` },
    copyrightHolder: { '@id': `${SITE.url}/#business` },
    creditText: SITE.name,
    copyrightNotice: `© ${new Date().getFullYear()} ${SITE.name}`,
    acquireLicensePage: `${SITE.url}/contact`,
    license: `${SITE.url}/terms`,
    contentLocation: {
      '@type': 'Place',
      name: opts.contentLocation ?? 'Taj Mahal',
      address: { '@type': 'PostalAddress', addressLocality: 'Agra', addressRegion: 'Uttar Pradesh', addressCountry: 'IN' },
    },
  };
}

/**
 * A clip, described for video search. Without duration, a thumbnail and an
 * upload date a <video> is invisible to Google; with them it can surface as a
 * video result, which nothing else on this site competes for.
 */
export function videoObjectSchema(opts: {
  name: string;
  description: string;
  contentUrl: string;
  thumbnailUrl: string;
  /** ISO 8601, e.g. PT27S */
  duration: string;
  uploadDate: string;
}) {
  return {
    '@type': 'VideoObject',
    name: opts.name,
    description: opts.description,
    contentUrl: opts.contentUrl,
    thumbnailUrl: [opts.thumbnailUrl],
    duration: opts.duration,
    uploadDate: opts.uploadDate,
    publisher: { '@id': `${SITE.url}/#business` },
    isFamilyFriendly: true,
    inLanguage: 'en',
  };
}

export function speakableSpec(cssSelectors: string[]) {
  return {
    '@type': 'SpeakableSpecification',
    cssSelector: cssSelectors,
  };
}

/** HowTo schema for "How to book" / "How to plan" pages. */
export function howToSchema(opts: {
  name: string;
  description: string;
  totalTime?: string;
  estimatedCost?: { value: number; currency?: string };
  steps: { name: string; text: string; url?: string }[];
}) {
  return {
    '@context': 'https://schema.org',
    '@type': 'HowTo',
    name: opts.name,
    description: opts.description,
    ...(opts.totalTime ? { totalTime: opts.totalTime } : {}),
    ...(opts.estimatedCost
      ? {
          estimatedCost: {
            '@type': 'MonetaryAmount',
            currency: opts.estimatedCost.currency ?? 'USD',
            value: opts.estimatedCost.value,
          },
        }
      : {}),
    step: opts.steps.map((s, i) => ({
      '@type': 'HowToStep',
      position: i + 1,
      name: s.name,
      text: s.text,
      ...(s.url ? { url: s.url } : {}),
    })),
  };
}

/** WebPage schema with `lastReviewed` — freshness signal AI engines reward. */
export function webPageSchema(opts: {
  url: string;
  name: string;
  description: string;
  image?: string;
  lastReviewed?: string;
  speakableSelectors?: string[];
  isPartOf?: string;
}) {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebPage',
    '@id': `${opts.url}#webpage`,
    url: opts.url,
    name: opts.name,
    description: opts.description,
    inLanguage: 'en-US',
    isPartOf: { '@id': opts.isPartOf ?? `${SITE.url}/#website` },
    about: { '@id': `${SITE.url}/#business` },
    primaryImageOfPage: opts.image
      ? { '@type': 'ImageObject', url: opts.image }
      : undefined,
    lastReviewed: opts.lastReviewed,
    reviewedBy: { '@id': `${SITE.url}/#photographer` },
    publisher: { '@id': `${SITE.url}/#business` },
    speakable: opts.speakableSelectors
      ? speakableSpec(opts.speakableSelectors)
      : undefined,
  };
}

/** Wrap multiple schema objects into a single @graph — preferred by AI parsers. */
export function graphSchema(nodes: Record<string, unknown>[]) {
  return {
    '@context': 'https://schema.org',
    '@graph': nodes.map((n) => {
      const copy = { ...n };
      delete (copy as Record<string, unknown>)['@context'];
      return copy;
    }),
  };
}

/** Helper to render a JSON-LD script tag */
export function jsonLd(data: Record<string, unknown> | Record<string, unknown>[]) {
  return JSON.stringify(data);
}
